package cloudutils4j.exceptions.s3.invalid.localpath;

public class NullLocalPathException extends RuntimeException {
    public NullLocalPathException(String message) { super(message); }
}
